# Generated by Django 5.1.7 on 2025-05-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensores',
            old_name='mac_adress',
            new_name='mac_address',
        ),
    ]
