# Generated by Django 5.1.7 on 2025-05-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_mac_adress_sensores_mac_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicos',
            old_name='Valor',
            new_name='valor',
        ),
    ]
