# Generated by Django 5.1.7 on 2025-05-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_valor_historicos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicos',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
